### ISSUE TITLE
using docx format in cloud

### ISSUE THREAD

**Issue by acsankar** [DS4SD/docling-core#72] opened 2024-11-22 00:56 UTC
I am trying to use this in cloud and just trying to convert it to markdown without images. Assuming below error is coming when there are images in document. Any suggestions to fix this? 

doc_converter = DocumentConverter(
    allowed_formats=[InputFormat.DOCX],
    format_options={
        InputFormat.DOCX: WordFormatOption(pipeline_cls=SimplePipeline),
    },
)

I am getting below error 
---> 30 result = doc_converter.convert(temp_file.name)

18 frames
[/usr/local/lib/python3.10/dist-packages/PIL/ImageFile.py](https://localhost:8080/#) in load(self)
    375         if loader is None:
    376             msg = f"cannot find loader for this {self.format} file"
--> 377             raise OSError(msg)
    378         image = loader.load(self)
    379         assert image is not None

OSError: cannot find loader for this WMF file

**Comment by cau-git** [comment] 2024-11-25 13:27
This seems to be a duplicate of https://github.com/DS4SD/docling/issues/410, closing here.

**Closed by cau-git** 2024-11-25 13:27 UTC

**Comment by maxmnemonic** [comment] 2024-11-25 16:13
I think the most likely problem here is that word file includes an image, blob of which can't be loaded by PIL library.
Error should trigger, even if file would be fully local.

@acsankar, any chance you could make an example file for this error?
